#ifndef NETWORK_CONFIG_H
#define NETWORK_CONFIG_H

#define NM_CLIENT_HANDLER_SERVER_IP "127.0.0.1"
#define NM_CLIENT_HANDLER_SERVER_PORT 8000
#define NM_CLIENT_HANDLER_TCP_WAIT_QUEUE_LENGTH 5

#endif // NETWORK_CONFIG_H